---
version: '2'
services:
  db:
    image: mariadb:10.3
    ports:
    - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: bestpractices
        MYSQL_USER: tsq
        MYSQL_PASSWORD: 1234
  sonarqube:
    image: sonarqube:latest
    ports:
    - "9000:9000"
    - "9092:9092"